use std::path::PathBuf;
use std::fs;

fn main() {
    // Get the workspace root by going up from CARGO_MANIFEST_DIR
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent().map(|p| p.parent()).flatten()
        .unwrap_or_else(|| &manifest_dir);

    let wiztree_src = workspace_root.join("WizTree.exe");
    
    // Tell cargo to rerun if WizTree.exe changes
    if wiztree_src.exists() {
        println!("cargo:rerun-if-changed={}", wiztree_src.display());
    }
    
    // Get output directory from cargo  
    let out_dir = std::env::var("OUT_DIR").unwrap_or_else(|_| ".".to_string());
    let out_path = PathBuf::from(&out_dir);
    
    if wiztree_src.exists() {
        match fs::read(&wiztree_src) {
            Ok(data) => {
                println!("cargo:warning=Embedding WizTree.exe ({} bytes) into binary", data.len());
                
                // Generate Rust code that embeds the WizTree binary as base64
                let encoded = base64_encode(&data);
                
                let rs_code = format!(
                    "// Auto-generated by build.rs - Do not edit!\n\
                     /// Embedded WizTree.exe binary (base64 encoded)\n\
                     pub const WIZTREE_BINARY_B64: &str = r#\"{}\"#;\n\
                     pub const WIZTREE_EMBEDDED: bool = true;\n",
                    encoded
                );
                
                let rs_path = out_path.join("wiztree_embedded.rs");
                match fs::write(&rs_path, rs_code) {
                    Ok(_) => {
                        println!("cargo:warning=Successfully embedded WizTree.exe into binary");
                    }
                    Err(e) => {
                        println!("cargo:warning=Failed to generate WizTree embed file: {}", e);
                    }
                }
            }
            Err(e) => {
                // Generate stub that indicates WizTree is not embedded
                let stub = "pub const WIZTREE_BINARY_B64: &str = \"\";\npub const WIZTREE_EMBEDDED: bool = false;\n";
                let _ = fs::write(out_path.join("wiztree_embedded.rs"), stub);
                println!("cargo:warning=WizTree.exe found but unreadable: {}", e);
            }
        }
    } else {
        // Generate stub that indicates WizTree is not embedded
        let stub = "pub const WIZTREE_BINARY_B64: &str = \"\";\npub const WIZTREE_EMBEDDED: bool = false;\n";
        let _ = fs::write(out_path.join("wiztree_embedded.rs"), stub);
        println!("cargo:warning=WizTree.exe not found - will look for external binary");
    }
}

/// Simple base64 encoding for embedding binary data
fn base64_encode(data: &[u8]) -> String {
    const BASE64_TABLE: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut result = String::new();
    
    for chunk in data.chunks(3) {
        let b1 = chunk[0];
        let b2 = chunk.get(1).copied().unwrap_or(0);
        let b3 = chunk.get(2).copied().unwrap_or(0);
        
        let n = ((b1 as u32) << 16) | ((b2 as u32) << 8) | (b3 as u32);
        
        result.push(BASE64_TABLE[((n >> 18) & 0x3F) as usize] as char);
        result.push(BASE64_TABLE[((n >> 12) & 0x3F) as usize] as char);
        result.push(if chunk.len() > 1 { BASE64_TABLE[((n >> 6) & 0x3F) as usize] as char } else { '=' });
        result.push(if chunk.len() > 2 { BASE64_TABLE[(n & 0x3F) as usize] as char } else { '=' });
    }
    
    result
}
