use std::collections::HashMap;
use std::path::PathBuf;
use std::process::Command;
use std::fs;
use std::io::{BufRead, BufReader};
use std::ffi::OsStr;

use csv::ReaderBuilder;

use crate::normalize::ext_key;
use crate::root::Root;
use crate::walk::WalkRec;
use crate::error::{Error, Result};

// Include embedded WizTree binary data (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/wiztree_embedded.rs"));

/// Directory mtime from a previous catalog, keyed by relative path with `/`.
pub type DirMtimes = HashMap<String, i64>;

/// Call WizTree command line to scan a directory and parse CSV output
pub fn walk_root_wiztree(
    root: &Root,
    _prev: &DirMtimes,
    _pruned: &mut Vec<String>,
) -> Result<Vec<WalkRec>> {
    // Find WizTree executable
    let wiztree_exe = find_wiztree_exe()?;
    
    // Create a temporary CSV file path using system temp directory with timestamp
    // to avoid conflicts if multiple instances run with same PID
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    let csv_filename = format!("utfsearch_export_{}_{}.csv", std::process::id(), timestamp);
    let csv_path = {
        let temp = std::env::var("TEMP")
            .or_else(|_| std::env::var("TMP"))
            .unwrap_or_else(|_| "C:\\Windows\\Temp".to_string());
        PathBuf::from(&temp).join(&csv_filename)
    };
    let csv_path_str = csv_path.to_string_lossy().to_string();
    
    // Build the WizTree command
    let mut cmd = Command::new(&wiztree_exe);
    
    // Add the path to scan - use as_os_str() to preserve encoding
    cmd.arg(root.path.as_os_str());
    
    // Add export parameter
    cmd.arg(format!("/export={}", csv_path_str));
    cmd.arg("/admin=1");
    cmd.arg("/exportfiles=1");
    cmd.arg("/exportfolders=1");
    
    // Add filters if needed
    if !root.excludes.is_empty() {
        let exclude_filter = root.excludes.join("|");
        cmd.arg(format!("/filterexclude={}", exclude_filter));
    }
    
    // Execute the scan - MUST wait for completion
    eprintln!("Executing WizTree: {:?}", wiztree_exe);
    eprintln!("WizTree root: {:?}", root.path);
    eprintln!("WizTree csv path: {}", csv_path_str);
    
    let start_time = std::time::Instant::now();
    let output = cmd.output()
        .map_err(|e| Error::Io(e))?;
    let elapsed = start_time.elapsed();
    
    eprintln!("WizTree completed in {:?}", elapsed);
    eprintln!("WizTree exit code: {:?}", output.status.code());
    
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        eprintln!("WizTree FAILED!");
        eprintln!("WizTree stderr: {}", stderr);
        eprintln!("WizTree stdout: {}", stdout);
    }
    
    // Wait for file to be fully flushed and readable - no time limit for large directories
    let mut wait_time = 0;
    let max_wait = u64::MAX; // No hard limit - allow arbitrarily long waits for large directories
    let check_interval = 100; // Check every 100ms
    
    while wait_time < max_wait {
        std::thread::sleep(std::time::Duration::from_millis(check_interval));
        wait_time += check_interval;
        
        if csv_path.exists() {
            // File exists - try to open it to see if it's locked
            match fs::File::open(&csv_path) {
                Ok(_) => {
                    if wait_time > 2000 {
                        eprintln!("CSV file ready after {}ms", wait_time);
                    }
                    break;
                }
                Err(e) if e.raw_os_error() == Some(32) => {
                    // File locked - keep waiting silently
                }
                Err(e) => {
                    eprintln!("Error checking CSV file: {}", e);
                }
            }
        }
    }
    
    // Final check - verify file was created
    if !csv_path.exists() {
        eprintln!("ERROR: CSV file still does not exist after waiting {}ms", wait_time);
        eprintln!("Checking file system...");
        
        // Try to list temp directory to debug
        if let Some(parent) = csv_path.parent() {
            if let Ok(entries) = fs::read_dir(parent) {
                eprintln!("Files in temp directory:");
                for entry in entries.flatten() {
                    if let Ok(name) = entry.file_name().into_string() {
                        if name.contains("utfsearch") {
                            eprintln!("  - {}", name);
                        }
                    }
                }
            }
        }
        
        return Err(Error::Msg(format!(
            "WizTree CSV file not created at: {} (exit code: {:?}, waited: {}ms)",
            csv_path_str, 
            output.status.code(),
            wait_time
        )));
    }
    
    // Parse the CSV file
    let result = parse_wiztree_csv(&csv_path_str, root);
    
    // Schedule cleanup for later - file might still be locked by WizTree or antivirus
    // Try immediate deletion, but don't fail if it's locked
    std::thread::sleep(std::time::Duration::from_millis(500));
    
    for attempt in 0..5 {
        match fs::remove_file(&csv_path) {
            Ok(_) => {
                eprintln!("CSV file deleted successfully");
                break;
            }
            Err(e) => {
                if attempt < 4 {
                    eprintln!("Failed to delete CSV (attempt {}): {}, retrying in 500ms...", attempt + 1, e);
                    std::thread::sleep(std::time::Duration::from_millis(500));
                } else {
                    // Last attempt - log but don't fail
                    eprintln!("Warning: Could not delete temporary CSV file after 5 attempts: {}", e);
                    eprintln!("File will remain in temp directory: {}", csv_path_str);
                }
            }
        }
    }
    
    // Clean up temporary WizTree binary if it was extracted from embedded data
    if wiztree_exe.to_string_lossy().contains("utfsearch_wiztree_") {
        // Give WizTree process extra time to fully release the file
        std::thread::sleep(std::time::Duration::from_millis(1000));
        
        for attempt in 0..10 {
            match fs::remove_file(&wiztree_exe) {
                Ok(_) => {
                    eprintln!("Temporary WizTree binary deleted: {:?}", wiztree_exe);
                    break;
                }
                Err(e) => {
                    if attempt < 9 {
                        let delay = 500 * (attempt + 1); // Progressive backoff: 500ms, 1000ms, 1500ms...
                        eprintln!("Failed to delete temporary WizTree (attempt {}): {}, retrying in {}ms...", attempt + 1, e, delay);
                        std::thread::sleep(std::time::Duration::from_millis(delay));
                    } else {
                        // Last attempt - just log, don't fail the operation
                        eprintln!("Warning: Could not delete temporary WizTree after 10 attempts: {}", e);
                        eprintln!("File will remain in temp directory: {:?}", wiztree_exe);
                    }
                }
            }
        }
    }
    
    result
}

/// Find WizTree.exe in standard locations, or extract from embedded binary
fn find_wiztree_exe() -> Result<PathBuf> {
    // 1. Try current directory
    let candidates = vec![
        PathBuf::from("WizTree.exe"),
        PathBuf::from("WizTree64.exe"),
        PathBuf::from("./WizTree.exe"),
        PathBuf::from("./WizTree64.exe"),
    ];
    
    for candidate in candidates {
        if candidate.exists() {
            eprintln!("Found WizTree at: {:?}", candidate);
            return Ok(candidate);
        }
    }
    
    // 2. Try same directory as the executable
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            let wiztree_exe = exe_dir.join("WizTree.exe");
            let wiztree_64 = exe_dir.join("WizTree64.exe");
            
            if wiztree_exe.exists() {
                eprintln!("Found WizTree at exe directory: {:?}", wiztree_exe);
                return Ok(wiztree_exe);
            }
            if wiztree_64.exists() {
                eprintln!("Found WizTree64 at exe directory: {:?}", wiztree_64);
                return Ok(wiztree_64);
            }
        }
    }
    
    // 3. Try to find in environment PATH
    if let Ok(path_env) = std::env::var("PATH") {
        for path_dir in path_env.split(';') {
            let wiztree_path = PathBuf::from(path_dir).join("WizTree64.exe");
            if wiztree_path.exists() {
                eprintln!("Found WizTree64 in PATH: {:?}", wiztree_path);
                return Ok(wiztree_path);
            }
            let wiztree_path = PathBuf::from(path_dir).join("WizTree.exe");
            if wiztree_path.exists() {
                eprintln!("Found WizTree in PATH: {:?}", wiztree_path);
                return Ok(wiztree_path);
            }
        }
    }
    
    // 4. Try to extract from embedded binary if available
    if WIZTREE_EMBEDDED && !WIZTREE_BINARY_B64.is_empty() {
        eprintln!("Extracting embedded WizTree from binary...");
        
        // Decode base64
        if let Ok(binary_data) = base64_decode(WIZTREE_BINARY_B64) {
            // Write to temp directory
            let temp_wiztree = {
                let temp = std::env::var("TEMP")
                    .or_else(|_| std::env::var("TMP"))
                    .unwrap_or_else(|_| "C:\\Windows\\Temp".to_string());
                PathBuf::from(&temp).join(format!("utfsearch_wiztree_{}.exe", std::process::id()))
            };
            
            match fs::write(&temp_wiztree, &binary_data) {
                Ok(_) => {
                    eprintln!("Successfully extracted WizTree to: {:?}", temp_wiztree);
                    return Ok(temp_wiztree);
                }
                Err(e) => {
                    eprintln!("Failed to extract embedded WizTree: {}", e);
                }
            }
        } else {
            eprintln!("Failed to decode embedded WizTree binary");
        }
    }
    
    Err(Error::Msg(
        "WizTree.exe not found and not embedded. Please ensure WizTree is installed or placed in the same directory as utfsearch.exe.".into(),
    ))
}

/// Simple base64 decoder
fn base64_decode(s: &str) -> Result<Vec<u8>> {
    let mut result = Vec::new();
    let mut buffer = 0u32;
    let mut bits = 0;
    
    for c in s.chars() {
        if c.is_whitespace() {
            continue;
        }
        
        let val = match c {
            'A'..='Z' => (c as u32) - ('A' as u32),
            'a'..='z' => (c as u32) - ('a' as u32) + 26,
            '0'..='9' => (c as u32) - ('0' as u32) + 52,
            '+' => 62,
            '/' => 63,
            '=' => break,
            _ => return Err(Error::Msg("Invalid base64 character".into())),
        };
        
        buffer = (buffer << 6) | val;
        bits += 6;
        
        if bits >= 8 {
            bits -= 8;
            result.push((buffer >> bits) as u8);
            buffer &= (1 << bits) - 1;
        }
    }
    
    Ok(result)
}

// List of common directories and files to exclude from indexing
use crate::skip::{ALWAYS, SKIP_FILES};

fn should_exclude(rel_path: &str, is_dir: bool) -> bool {
    let parts: Vec<&str> = rel_path.split('/').collect();
    
    // Check each path component against ALWAYS skip list
    for part in &parts {
        if ALWAYS.iter().any(|e| e.eq_ignore_ascii_case(part)) {
            return true;
        }
    }
    
    // Check if it's a file that should be skipped
    if !is_dir {
        if let Some(last_part) = parts.last() {
            if SKIP_FILES.iter().any(|f| f.eq_ignore_ascii_case(last_part)) {
                return true;
            }
        }
    }
    
    false
}

fn parse_wiztree_csv(csv_path: &str, root: &Root) -> Result<Vec<WalkRec>> {
    // Open file once and process it completely
    let file = fs::File::open(csv_path)
        .map_err(|e| Error::Io(e))?;
    
    let buf_reader = BufReader::new(file);
    let mut lines = buf_reader.lines();
    
    // Skip the "Generated by WizTree..." comment line
    if let Some(first_line) = lines.next() {
        match first_line {
            Ok(line) => eprintln!("CSV header: {}", line),
            Err(e) => eprintln!("Error reading first line: {}", e),
        }
    }
    
    // Collect remaining lines for CSV parsing
    let remaining_lines: String = lines
        .filter_map(|line| line.ok())
        .collect::<Vec<_>>()
        .join("\n");
    
    // Create CSV reader from the collected lines
    let mut csv_reader = ReaderBuilder::new()
        .has_headers(true)
        .flexible(true)  // Allow variable number of fields per record
        .from_reader(remaining_lines.as_bytes());
    
    let mut records = Vec::new();
    let root_path_str = root.path.to_string_lossy().to_string();
    let mut excluded_count = 0u64;
    
    for result in csv_reader.records() {
        let record = match result {
            Ok(r) => r,
            Err(e) => {
                eprintln!("CSV record error: {}", e);
                continue;
            }
        };
        
        if record.len() < 4 {
            continue;
        }
        
        let file_name_col = &record[0];  // File Name (full path with backslashes)
        let size_str = &record[1];       // Size
        let _allocated_str = &record[2]; // Allocated
        let modified_str = &record[3];  // Modified
        
        // Parse size (remove leading 0 for hard links)
        let size_bytes = parse_size_bytes(size_str);
        
        // Determine if it's a directory (name ends with \)
        let is_dir = file_name_col.ends_with('\\');
        let path_str = if is_dir {
            &file_name_col[..file_name_col.len() - 1]
        } else {
            file_name_col
        };
        
        // Check if this file is within the root - compare as PathBufs for proper encoding
        let file_path = PathBuf::from(path_str);
        if !file_path.starts_with(&root.path) {
            // Try case-insensitive comparison for Windows
            let file_lower = path_str.to_lowercase().replace('\\', "/");
            let root_lower = root_path_str.to_lowercase().replace('\\', "/");
            if !file_lower.starts_with(&root_lower) {
                continue;
            }
        }
        
        // Calculate relative path
        let rel = {
            let file_normalized = path_str.replace('\\', "/");
            let root_normalized = root_path_str.replace('\\', "/");
            
            if file_normalized.to_lowercase().starts_with(&root_normalized.to_lowercase()) {
                let skip_len = root_normalized.len();
                let rel_part = &file_normalized[skip_len..];
                rel_part.trim_start_matches('/').to_string()
            } else {
                continue;
            }
        };
        
        if rel.is_empty() {
            continue;
        }
        
        // Check if this entry should be excluded
        if should_exclude(&rel, is_dir) {
            excluded_count += 1;
            continue;
        }
        
        // Extract file name
        let name = if is_dir {
            rel.split('/').last().unwrap_or("").to_string()
        } else {
            rel.split('/').last().unwrap_or("").to_string()
        };
        
        if name.is_empty() {
            continue;
        }
        
        // Parse modified time (format: yyyy/mm/dd HH:mm:ss)
        let mtime = parse_mtime(modified_str);
        let mtime_millis = mtime * 1000;
        
        // Extract extension for files
        let ext = if !is_dir {
            if let Some(dot_pos) = name.rfind('.') {
                let ext_part = &name[dot_pos + 1..];
                ext_key(&ext_part.to_lowercase())
            } else {
                String::new()
            }
        } else {
            String::new()
        };
        
        records.push(WalkRec {
            rel,
            name,
            ext,
            owner: String::new(), // WizTree CSV doesn't include owner info
            is_dir,
            is_symlink: false, // WizTree doesn't expose symlinks in CSV
            size: if is_dir { 0 } else { size_bytes },
            mtime,
            mtime_fine: mtime_millis,
            mtime_missing: mtime == 0,
            non_utf8: false, // CSV is UTF-8
        });
    }
    
    if excluded_count > 0 {
        eprintln!("Excluded {} entries matching exclusion patterns", excluded_count);
    }
    
    Ok(records)
}

fn parse_size_bytes(size_str: &str) -> u64 {
    let trimmed = size_str.trim();
    if trimmed.is_empty() || trimmed == "0" {
        return 0;
    }
    
    // Handle leading 0 for hard links (WizTree format)
    let clean = if trimmed.starts_with('0') && trimmed.len() > 1 && trimmed.chars().nth(1).unwrap().is_digit(10) {
        &trimmed[1..]
    } else {
        trimmed
    };
    
    clean.parse::<u64>().unwrap_or(0)
}

fn parse_mtime(mtime_str: &str) -> i64 {
    // Format: yyyy/mm/dd HH:mm:ss
    // Convert to Unix timestamp
    
    if mtime_str.is_empty() || mtime_str == "0" {
        return 0;
    }
    
    // Try to parse using chrono-like logic
    let parts: Vec<&str> = mtime_str.split_whitespace().collect();
    if parts.len() < 2 {
        return 0;
    }
    
    let date_parts: Vec<&str> = parts[0].split('/').collect();
    if date_parts.len() < 3 {
        return 0;
    }
    
    let year = date_parts[0].parse::<i32>().unwrap_or(1970);
    let month = date_parts[1].parse::<u32>().unwrap_or(1);
    let day = date_parts[2].parse::<u32>().unwrap_or(1);
    
    let time_parts: Vec<&str> = parts[1].split(':').collect();
    let hour = if time_parts.len() > 0 { time_parts[0].parse::<u32>().unwrap_or(0) } else { 0 };
    let minute = if time_parts.len() > 1 { time_parts[1].parse::<u32>().unwrap_or(0) } else { 0 };
    let second = if time_parts.len() > 2 { time_parts[2].parse::<u32>().unwrap_or(0) } else { 0 };
    
    // Simple approximation (proper implementation would need chrono or time crate)
    // This calculates seconds since Unix epoch (1970-01-01)
    // days_since_epoch gives days since 2000-01-01, so we add the offset
    let days_since_2000 = days_since_epoch(year, month, day);
    let seconds_since_2000 = (days_since_2000 as i64) * 86400 + (hour as i64 * 3600) + (minute as i64 * 60) + (second as i64);
    
    // Adjust to Unix epoch (1970): add the seconds from 1970-01-01 to 2000-01-01
    946684800 + seconds_since_2000 // Seconds between 1970 and 2000
}

fn days_since_epoch(year: i32, month: u32, day: u32) -> i32 {
    let mut days = 0;
    
    // Add days for complete years
    for y in 2000..year {
        days += if is_leap_year(y) { 366 } else { 365 };
    }
    
    // Add days for complete months in current year
    let days_in_month = [31, if is_leap_year(year) { 29 } else { 28 }, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    for m in 1..month {
        days += days_in_month[(m - 1) as usize] as i32;
    }
    
    // Add remaining days
    days += day as i32;
    
    days
}

fn is_leap_year(year: i32) -> bool {
    (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)
}
